### ISSUE TITLE
Unable to install Symfony at the root (at the same level of the docker-compose file)

### ISSUE THREAD

**Issue by coolfarmer** [bitnami/bitnami-docker-symfony#65]
**Description**

I can't have my project at the same level of the docker-compose file.
My docker-compose file is at _C:/working_directory/MyApp/docker-compose.yml_

When I **docker-compose up** on this file, it create my symfony project in a directory : _C:/working_directory/MyApp/MyApp_

So the final structure is:
```
- MyApp
- docker-compose-yml
-- MyApp
---bin
---config
---vendor
---...
```

The dupplicate name is pretty bad, I should have the symfony project at the SAME level as the docker-compose.yml, without another directory with the same app name.

Is it possible to achieve that behavior?

Thanks.

**Comment by rafariossaa** [comment]
Hi @coolfarmer ,
  Could you share your docker-compose.yml file ?

**Comment by coolfarmer** [comment]
> 
> 
> Hi @coolfarmer ,
> Could you share your docker-compose.yml file ?

Yes, here is it: https://pastebin.com/ZYjMnbuj

My goal is to have my docker-compose.yml file at the SAME level of the symfony project.

**Comment by rafariossaa** [comment]
Hi,
  My advice is not to put the docker-compose file at the same level that the project code. The reason is that in that case it could be accessible by the application or by someone that hack the application, and you can have passwords or other sensible information in that file. Even you can move the docker-file to other location and you just need to configure the volume path to where you store your projects.
  Anyways this is a configurable thing and you can set it in your preferred way, so in order to answer you question, I used this docker-compose file in a directory called `test`:


```
...
simtp:
    image: 'bitnami/symfony:1'
    ports:
      - '8780:8000'
    volumes:
      - '../:/app'
    environment:
      - TZ=America/New_York
      - SYMFONY_PROJECT_NAME=test
...
```
